# Generated by Django 5.2.6 on 2025-10-12 23:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('divisas', '0002_initial'),
        ('transacciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código identificador de la terminal', max_length=20, unique=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('is_activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminales_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PINTerminalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='PIN de 6 dígitos', max_length=6)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha y hora de expiración del PIN')),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pines_terminal', to='clientes.cliente')),
                ('terminal_usada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tauser.terminal')),
            ],
            options={
                'verbose_name': 'PIN de Terminal',
                'verbose_name_plural': 'PINs de Terminal',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='InventarioDivisaTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Cantidad disponible en esta terminal', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cantidad_minima', models.DecimalField(decimal_places=8, default=Decimal('100.00'), help_text='Cantidad mínima de alerta', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones_inventario', to=settings.AUTH_USER_MODEL)),
                ('divisa', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='tauser.terminal')),
            ],
            options={
                'verbose_name': 'Inventario de Divisa por Terminal',
                'verbose_name_plural': 'Inventarios de Divisa por Terminal',
                'ordering': ['terminal', 'divisa'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTransaccionTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('RETIRO', 'Retiro de Divisa'), ('PAGO', 'Pago/Depósito'), ('CONSULTA', 'Consulta')], max_length=20)),
                ('monto_operacion', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fue_exitoso', models.BooleanField(default=False)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_terminal', to='clientes.cliente')),
                ('divisa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa')),
                ('pin_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tauser.pinterminalcliente')),
                ('transaccion_original', models.ForeignKey(blank=True, help_text='Transacción del sistema relacionada', null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.transaccion')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='tauser.terminal')),
            ],
            options={
                'verbose_name': 'Registro de Operación en Terminal',
                'verbose_name_plural': 'Registros de Operaciones en Terminal',
                'ordering': ['-fecha_operacion'],
                'indexes': [models.Index(fields=['terminal', 'fecha_operacion'], name='tauser_regi_termina_84e255_idx'), models.Index(fields=['cliente', 'fecha_operacion'], name='tauser_regi_cliente_206910_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pinterminalcliente',
            index=models.Index(fields=['pin', 'usado'], name='tauser_pint_pin_9f72ac_idx'),
        ),
        migrations.AddIndex(
            model_name='pinterminalcliente',
            index=models.Index(fields=['cliente', 'fecha_expiracion'], name='tauser_pint_cliente_0db37a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventariodivisaterminal',
            unique_together={('terminal', 'divisa')},
        ),
    ]
