# Generated by Django 5.2.6 on 2025-10-30 19:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioDenominacionTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Cantidad de billetes disponibles', verbose_name='Cantidad de billetes')),
                ('cantidad_minima', models.PositiveIntegerField(default=10, help_text='Alerta cuando la cantidad sea menor a este valor', verbose_name='Cantidad mínima')),
                ('ultima_reposicion', models.DateTimeField(blank=True, null=True, verbose_name='Última reposición')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventario de denominación',
                'verbose_name_plural': 'Inventarios de denominaciones',
                'ordering': ['terminal', '-denominacion__valor'],
            },
        ),
        migrations.CreateModel(
            name='InventarioDivisaTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Cantidad disponible en esta terminal', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cantidad_minima', models.DecimalField(decimal_places=8, default=Decimal('100.00'), help_text='Cantidad mínima de alerta', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventario de Divisa por Terminal',
                'verbose_name_plural': 'Inventarios de Divisa por Terminal',
                'ordering': ['terminal', 'divisa'],
            },
        ),
        migrations.CreateModel(
            name='PINTerminalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='PIN de 6 dígitos', max_length=6)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha y hora de expiración del PIN')),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PIN de Terminal',
                'verbose_name_plural': 'PINs de Terminal',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTransaccionTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('RETIRO', 'Retiro de Divisa'), ('PAGO', 'Pago/Depósito'), ('CONSULTA', 'Consulta')], max_length=20)),
                ('monto_operacion', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fue_exitoso', models.BooleanField(default=False)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Operación en Terminal',
                'verbose_name_plural': 'Registros de Operaciones en Terminal',
                'ordering': ['-fecha_operacion'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código identificador de la terminal', max_length=20, unique=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('is_activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DesgloseDenominacionOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de billetes entregados/recibidos', verbose_name='Cantidad')),
                ('tipo_movimiento', models.CharField(choices=[('ENTREGA', 'Entrega al cliente'), ('RECEPCION', 'Recepción del cliente')], max_length=10, verbose_name='Tipo de movimiento')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_terminal', to='divisas.denominacion', verbose_name='Denominación')),
            ],
            options={
                'verbose_name': 'Desglose de operación',
                'verbose_name_plural': 'Desgloses de operaciones',
                'ordering': ['-denominacion__valor'],
            },
        ),
    ]
