# Generated by Django 5.2.6 on 2025-10-17 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0008_alter_denominacion_valor'),
        ('tauser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesgloseDenominacionOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de billetes entregados/recibidos', verbose_name='Cantidad')),
                ('tipo_movimiento', models.CharField(choices=[('ENTREGA', 'Entrega al cliente'), ('RECEPCION', 'Recepción del cliente')], max_length=10, verbose_name='Tipo de movimiento')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_terminal', to='divisas.denominacion', verbose_name='Denominación')),
                ('registro_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose_denominaciones', to='tauser.registrotransaccionterminal', verbose_name='Operación')),
            ],
            options={
                'verbose_name': 'Desglose de operación',
                'verbose_name_plural': 'Desgloses de operaciones',
                'ordering': ['-denominacion__valor'],
                'unique_together': {('registro_operacion', 'denominacion')},
            },
        ),
        migrations.CreateModel(
            name='InventarioDenominacionTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Cantidad de billetes disponibles', verbose_name='Cantidad de billetes')),
                ('cantidad_minima', models.PositiveIntegerField(default=10, help_text='Alerta cuando la cantidad sea menor a este valor', verbose_name='Cantidad mínima')),
                ('ultima_reposicion', models.DateTimeField(blank=True, null=True, verbose_name='Última reposición')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_terminal', to='divisas.denominacion', verbose_name='Denominación')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_denominaciones', to='tauser.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Inventario de denominación',
                'verbose_name_plural': 'Inventarios de denominaciones',
                'ordering': ['terminal', '-denominacion__valor'],
                'indexes': [models.Index(fields=['terminal', 'denominacion'], name='tauser_inve_termina_2d8101_idx'), models.Index(fields=['cantidad'], name='tauser_inve_cantida_1fc1ba_idx')],
                'unique_together': {('terminal', 'denominacion')},
            },
        ),
    ]
