# Generated by Django 5.2.6 on 2025-10-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('divisas', '0002_initial'),
        ('tauser', '0001_initial'),
        ('transacciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariodenominacionterminal',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='inventariodenominacionterminal',
            name='denominacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_terminal', to='divisas.denominacion', verbose_name='Denominación'),
        ),
        migrations.AddField(
            model_name='inventariodivisaterminal',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariodivisaterminal',
            name='divisa',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa'),
        ),
        migrations.AddField(
            model_name='pinterminalcliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pines_terminal', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='registrotransaccionterminal',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_terminal', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='registrotransaccionterminal',
            name='divisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa'),
        ),
        migrations.AddField(
            model_name='registrotransaccionterminal',
            name='pin_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tauser.pinterminalcliente'),
        ),
        migrations.AddField(
            model_name='registrotransaccionterminal',
            name='transaccion_original',
            field=models.ForeignKey(blank=True, help_text='Transacción del sistema relacionada', null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.transaccion'),
        ),
        migrations.AddField(
            model_name='desglosedenominacionoperacion',
            name='registro_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose_denominaciones', to='tauser.registrotransaccionterminal', verbose_name='Operación'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='usuario_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminales_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrotransaccionterminal',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='tauser.terminal'),
        ),
        migrations.AddField(
            model_name='pinterminalcliente',
            name='terminal_usada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tauser.terminal'),
        ),
        migrations.AddField(
            model_name='inventariodivisaterminal',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='tauser.terminal'),
        ),
        migrations.AddField(
            model_name='inventariodenominacionterminal',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_denominaciones', to='tauser.terminal', verbose_name='Terminal'),
        ),
        migrations.AlterUniqueTogether(
            name='desglosedenominacionoperacion',
            unique_together={('registro_operacion', 'denominacion')},
        ),
        migrations.AddIndex(
            model_name='registrotransaccionterminal',
            index=models.Index(fields=['terminal', 'fecha_operacion'], name='tauser_regi_termina_84e255_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotransaccionterminal',
            index=models.Index(fields=['cliente', 'fecha_operacion'], name='tauser_regi_cliente_206910_idx'),
        ),
        migrations.AddIndex(
            model_name='pinterminalcliente',
            index=models.Index(fields=['pin', 'usado'], name='tauser_pint_pin_9f72ac_idx'),
        ),
        migrations.AddIndex(
            model_name='pinterminalcliente',
            index=models.Index(fields=['cliente', 'fecha_expiracion'], name='tauser_pint_cliente_0db37a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventariodivisaterminal',
            unique_together={('terminal', 'divisa')},
        ),
        migrations.AddIndex(
            model_name='inventariodenominacionterminal',
            index=models.Index(fields=['terminal', 'denominacion'], name='tauser_inve_termina_2d8101_idx'),
        ),
        migrations.AddIndex(
            model_name='inventariodenominacionterminal',
            index=models.Index(fields=['cantidad'], name='tauser_inve_cantida_1fc1ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventariodenominacionterminal',
            unique_together={('terminal', 'denominacion')},
        ),
    ]
