# Generated by Django 5.2.6 on 2025-12-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('divisas', '0002_initial'),
        ('tauser', '0002_initial'),
        ('transacciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventarioTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('RECARGA', 'Recarga Manual'), ('DEPOSITO', 'Depósito de Cliente'), ('EXTRACCION', 'Extracción/Retiro')], max_length=15, verbose_name='Tipo de Movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente asociado (solo para depósitos y extracciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_tauser', to='clientes.cliente', verbose_name='Cliente')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='tauser.terminal', verbose_name='Terminal')),
                ('transaccion', models.ForeignKey(blank=True, help_text='Transacción relacionada (solo para depósitos y extracciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_tauser', to='transacciones.transaccion', verbose_name='Transacción')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la recarga (solo para recargas manuales)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario_tauser', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de billetes (positivo para ingreso, se usa para extracciones también)', verbose_name='Cantidad')),
                ('cantidad_anterior', models.IntegerField(help_text='Cantidad en stock antes del movimiento', verbose_name='Stock anterior')),
                ('cantidad_nueva', models.IntegerField(help_text='Cantidad en stock después del movimiento', verbose_name='Stock nuevo')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.denominacion', verbose_name='Denominación')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tauser.movimientoinventarioterminal', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento',
                'verbose_name_plural': 'Detalles de Movimientos',
                'ordering': ['-denominacion__valor'],
            },
        ),
        migrations.AddIndex(
            model_name='movimientoinventarioterminal',
            index=models.Index(fields=['terminal', '-fecha'], name='tauser_movi_termina_d39734_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventarioterminal',
            index=models.Index(fields=['tipo_movimiento', '-fecha'], name='tauser_movi_tipo_mo_bed672_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventarioterminal',
            index=models.Index(fields=['cliente', '-fecha'], name='tauser_movi_cliente_0cd242_idx'),
        ),
    ]
