# Generated by Django 5.2.6 on 2025-10-31 02:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0008_alter_denominacion_valor'),
        ('tauser', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecargaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('cantidad_agregada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad agregada')),
                ('cantidad_anterior', models.IntegerField(verbose_name='Cantidad antes de la recarga')),
                ('cantidad_nueva', models.IntegerField(verbose_name='Cantidad después de la recarga')),
                ('valor_total_agregado', models.DecimalField(decimal_places=2, help_text='Cantidad agregada × Valor denominación', max_digits=20, verbose_name='Valor total agregado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisas.denominacion', verbose_name='Denominación')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_recargas', to='tauser.terminal', verbose_name='Terminal')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la recarga')),
            ],
            options={
                'verbose_name': 'Log de Recarga de Inventario',
                'verbose_name_plural': 'Logs de Recargas de Inventario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['terminal', '-fecha'], name='tauser_logr_termina_8af5ba_idx'), models.Index(fields=['usuario', '-fecha'], name='tauser_logr_usuario_c89fe4_idx')],
            },
        ),
    ]
