# Generated by Django 5.2.6 on 2025-10-31 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0003_logrecargainventario'),
        ('transacciones', '0003_transaccion_tauser_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaInventarioDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad reservada')),
                ('estado', models.CharField(choices=[('RESERVED', 'Reservado'), ('RELEASED', 'Liberado'), ('CONSUMED', 'Consumido'), ('CANCELLED', 'Cancelado')], default='RESERVED', max_length=12, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='tauser.inventariodenominacionterminal', verbose_name='Inventario de denominación')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='tauser.terminal', verbose_name='Terminal')),
                ('transaccion', models.ForeignKey(blank=True, help_text='Transacción que reservó estos billetes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_denominaciones', to='transacciones.transaccion')),
            ],
            options={
                'verbose_name': 'Reserva de Inventario',
                'verbose_name_plural': 'Reservas de Inventario',
                'indexes': [models.Index(fields=['terminal', 'inventario', 'estado'], name='tauser_rese_termina_6ba0f7_idx'), models.Index(fields=['transaccion', 'estado'], name='tauser_rese_transac_5f31bd_idx')],
            },
        ),
    ]
