# Generated by Django 5.2.6 on 2025-10-31 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0004_reservainventariodenominacion'),
        ('transacciones', '0003_transaccion_tauser_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reservada', models.PositiveIntegerField(help_text='Cantidad de billetes reservados', verbose_name='Cantidad Reservada')),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('confirmada', 'Confirmada (Retirada)'), ('liberada', 'Liberada (Cancelada)')], default='reservada', max_length=15, verbose_name='Estado')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación/Liberación')),
                ('inventario_denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='tauser.inventariodenominacionterminal', verbose_name='Inventario de Denominación')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_denominaciones', to='tauser.terminal', verbose_name='Terminal')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_denominaciones', to='transacciones.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Reserva de Denominación',
                'verbose_name_plural': 'Reservas de Denominaciones',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.DeleteModel(
            name='ReservaInventarioDenominacion',
        ),
        migrations.AddIndex(
            model_name='reservadenominacion',
            index=models.Index(fields=['transaccion', 'estado'], name='tauser_rese_transac_e50c63_idx'),
        ),
        migrations.AddIndex(
            model_name='reservadenominacion',
            index=models.Index(fields=['terminal', 'estado'], name='tauser_rese_termina_8131d3_idx'),
        ),
    ]
