# Generated by Django 5.2.4 on 2025-09-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_segmento_alter_cliente_segmento'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Segmento',
        ),
    ]
