# Generated by Django 5.2.4 on 2025-08-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(default='General', max_length=50, verbose_name='Segmento'),
        ),
    ]
