# Generated by Django 5.2.4 on 2025-08-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
    ]
