# Generated by Django 5.2.4 on 2025-09-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ultimo_cliente_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
