# Generated by Django 5.2.4 on 2025-08-26 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociar_clientes_usuarios', '0002_remove_cliente_segmento_remove_cliente_usuarios_and_more'),
        ('users', '0003_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(through='asociar_clientes_usuarios.AsignacionCliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AsignacionCliente',
        ),
    ]
