# Generated by Django 5.2.4 on 2025-08-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociar_clientes_usuarios', '0003_alter_asignacioncliente_cliente'),
        ('users', '0004_alter_cliente_usuarios_delete_asignacioncliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
