# Generated by Django 5.2.6 on 2025-10-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Formato: 001-003-0000051', max_length=20, unique=True, verbose_name='Número de Factura')),
                ('establecimiento', models.CharField(default='001', max_length=3, verbose_name='Establecimiento')),
                ('punto_expedicion', models.CharField(default='003', max_length=3, verbose_name='Punto de Expedición')),
                ('numero_documento', models.CharField(help_text='Formato: 0000051', max_length=7, verbose_name='Número de Documento')),
                ('de_id', models.IntegerField(blank=True, null=True, verbose_name='ID en SQL Proxy')),
                ('cdc', models.CharField(blank=True, help_text='Código de Control asignado por SIFEN', max_length=50, null=True, verbose_name='CDC')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='borrador', max_length=15, verbose_name='Estado')),
                ('estado_sifen', models.CharField(blank=True, max_length=255, verbose_name='Estado SIFEN')),
                ('descripcion_sifen', models.TextField(blank=True, verbose_name='Descripción SIFEN')),
                ('error_sifen', models.TextField(blank=True, verbose_name='Error SIFEN')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación SIFEN')),
                ('url_kude_pdf', models.URLField(blank=True, help_text='URL para descargar el PDF de la factura', null=True, verbose_name='URL KuDE PDF')),
                ('url_kude_xml', models.URLField(blank=True, help_text='URL para descargar el XML firmado', null=True, verbose_name='URL KuDE XML')),
                ('datos_factura', models.JSONField(blank=True, default=dict, help_text='Datos completos utilizados para generar la factura', verbose_name='Datos de la Factura')),
            ],
            options={
                'verbose_name': 'Factura Electrónica',
                'verbose_name_plural': 'Facturas Electrónicas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
