# Generated by Django 5.2.7 on 2025-10-30 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion_electronica', '0001_initial'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='transaccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura_electronica', to='transacciones.transaccion'),
        ),
        migrations.AddIndex(
            model_name='facturaelectronica',
            index=models.Index(fields=['numero_factura'], name='facturacion_numero__e435e1_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaelectronica',
            index=models.Index(fields=['cdc'], name='facturacion_cdc_33eee4_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaelectronica',
            index=models.Index(fields=['estado'], name='facturacion_estado_7902ed_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaelectronica',
            index=models.Index(fields=['fecha_emision'], name='facturacion_fecha_e_755731_idx'),
        ),
    ]
