# Generated by Django 5.2.7 on 2025-10-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='cdc',
            field=models.CharField(blank=True, help_text='Código de Control asignado por SIFEN', max_length=50, null=True, verbose_name='CDC'),
        ),
    ]
