# Generated by Django 5.2.7 on 2025-10-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0003_alter_facturaelectronica_cdc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='url_kude_pdf',
            field=models.URLField(blank=True, help_text='URL para descargar el PDF de la factura', null=True, verbose_name='URL KuDE PDF'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='url_kude_xml',
            field=models.URLField(blank=True, help_text='URL para descargar el XML firmado', null=True, verbose_name='URL KuDE XML'),
        ),
    ]
