# Generated by Django 5.2.6 on 2025-09-30 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('color_principal', models.CharField(default='#1d3557', max_length=7)),
                ('color_secundario', models.CharField(default='#457b9d', max_length=7)),
                ('logo_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='banco.bancouser')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.entidadbancaria')),
            ],
        ),
        migrations.AddField(
            model_name='bancouser',
            name='entidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='banco.entidadbancaria'),
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('mes_vencimiento', models.PositiveSmallIntegerField()),
                ('anho_vencimiento', models.PositiveSmallIntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=2000000, max_digits=12)),
                ('saldo_usado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.entidadbancaria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_credito', to='banco.bancouser')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('mes_vencimiento', models.PositiveSmallIntegerField()),
                ('anho_vencimiento', models.PositiveSmallIntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_debito', to='banco.cuenta')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.entidadbancaria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_debito', to='banco.bancouser')),
            ],
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarjeta_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.tarjetacredito')),
                ('tarjeta_debito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.tarjetadebito')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='banco.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='banco.cuenta')),
            ],
        ),
    ]
