# Generated by Django 5.2.6 on 2025-12-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco', '0001_initial'),
        ('billetera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotarjeta',
            name='billetera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_banco', to='billetera.billetera'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, help_text='Cuenta que recibe el pago (ej: cuenta empresa para compras)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_recibidos_tarjeta', to='banco.cuenta'),
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.entidadbancaria'),
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_credito', to='banco.bancouser'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='tarjeta_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.tarjetacredito'),
        ),
        migrations.AddField(
            model_name='tarjetadebito',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_debito', to='banco.cuenta'),
        ),
        migrations.AddField(
            model_name='tarjetadebito',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.entidadbancaria'),
        ),
        migrations.AddField(
            model_name='tarjetadebito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_debito', to='banco.bancouser'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='tarjeta_debito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.tarjetadebito'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='cuenta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='banco.cuenta'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='cuenta_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='banco.cuenta'),
        ),
    ]
