# Generated by Django 5.2.4 on 2025-09-24 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='cuenta_destino',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='cuenta_origen',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('PAGO_DEBITO', 'Pago con Tarjeta de Débito'), ('PAGO_CREDITO', 'Pago con Tarjeta de Crédito')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='banco.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='banco.cuenta')),
            ],
        ),
        migrations.DeleteModel(
            name='PagoTarjeta',
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
        migrations.DeleteModel(
            name='Transferencia',
        ),
    ]
