# Generated by Django 5.2.4 on 2025-09-24 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_remove_tarjeta_cuenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='saldo_credito',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='saldo_debito',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('CUENTA_CORRIENTE', 'Cuenta Corriente')], default='DEBITO', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=7)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_con_tarjeta', to='banco.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='banco.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='banco.cuenta')),
            ],
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
