# Generated by Django 5.2.4 on 2025-09-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_entidadbancaria_bancouser_entidad_cuenta_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadbancaria',
            name='color_principal',
            field=models.CharField(default='#1d3557', max_length=7),
        ),
        migrations.AddField(
            model_name='entidadbancaria',
            name='color_secundario',
            field=models.CharField(default='#457b9d', max_length=7),
        ),
        migrations.AddField(
            model_name='entidadbancaria',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
