# Generated by Django 5.2.6 on 2025-10-17 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotarjeta',
            name='cuenta_destino',
            field=models.ForeignKey(blank=True, help_text='Cuenta que recibe el pago (ej: cuenta empresa para compras)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_recibidos_tarjeta', to='banco.cuenta'),
        ),
    ]
