# Generated by Django 5.2.4 on 2025-09-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_remove_cuenta_saldo_credito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagotarjeta',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.entidadbancaria'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], default='DEBITO', max_length=7),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='banco.bancouser'),
        ),
    ]
