# Generated by Django 5.2.4 on 2025-09-25 00:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_remove_pagotarjeta_descripcion_alter_cuenta_entidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaRecibidaBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billetera_origen', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas_desde_billetera', to='banco.cuenta')),
            ],
        ),
    ]
