# Generated by Django 5.2.4 on 2025-09-26 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_transferenciarecibidabilletera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_cuenta',
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=7)),
                ('numero_tarjeta', models.CharField(max_length=16, unique=True)),
                ('mes_vencimiento', models.PositiveSmallIntegerField()),
                ('anho_vencimiento', models.PositiveSmallIntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('cuenta', models.ForeignKey(blank=True, help_text='Solo se usa en tarjetas de débito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='banco.cuenta')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.entidadbancaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='banco.bancouser')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('mes_vencimiento', models.PositiveSmallIntegerField()),
                ('anho_vencimiento', models.PositiveSmallIntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.entidadbancaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_credito', to='banco.bancouser')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('mes_vencimiento', models.PositiveSmallIntegerField()),
                ('anho_vencimiento', models.PositiveSmallIntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.entidadbancaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_debito', to='banco.bancouser')),
            ],
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='banco.tarjetadebito'),
        ),
        migrations.DeleteModel(
            name='TransferenciaRecibidaBilletera',
        ),
    ]
