# Generated by Django 5.2.4 on 2025-09-26 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_remove_cuenta_tipo_cuenta_tarjeta_tarjetacredito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagotarjeta',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='pagotarjeta',
            name='tarjeta',
        ),
        migrations.RemoveField(
            model_name='pagotarjeta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='tarjeta_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.tarjetacredito'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='tarjeta_debito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.tarjetadebito'),
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=2000000, max_digits=12),
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='saldo_usado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tarjetadebito',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_debito', to='banco.cuenta'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_credito', to='banco.bancouser'),
        ),
        migrations.AlterField(
            model_name='tarjetadebito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_debito', to='banco.bancouser'),
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
