# Generated by Django 5.2.4 on 2025-10-07 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitar_notificaciones', models.BooleanField(default=True)),
                ('canal_notificacion', models.CharField(choices=[('sistema', 'Solo por el Sistema'), ('sistema_correo', 'Sistema y Correo Electrónico')], default='sistema', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_lectura', models.CharField(choices=[('pendiente', 'Pendiente'), ('leida', 'Leída')], default='pendiente', max_length=10)),
                ('correo_enviado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notificación de Usuario',
                'verbose_name_plural': 'Notificaciones de Usuario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa', models.CharField(max_length=5)),
                ('activa', models.BooleanField(default=True)),
                ('tipo_alerta', models.CharField(choices=[('general', 'Cambio General'), ('umbral', 'Alcanzar Umbral')], max_length=10)),
                ('tipo_operacion', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ambos', 'Compra y Venta')], max_length=10)),
                ('condicion_umbral', models.CharField(blank=True, choices=[('mayor', 'Mayor o igual que'), ('menor', 'Menor o igual que')], max_length=10, null=True)),
                ('monto_umbral', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Notificación de Tasa',
                'verbose_name_plural': 'Notificaciones de Tasa',
            },
        ),
    ]
