# Generated by Django 5.2.4 on 2025-10-12 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciontasa',
            name='dia_mes',
            field=models.IntegerField(blank=True, help_text='Solo para notificaciones mensuales (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='notificaciontasa',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Solo para notificaciones semanales', null=True),
        ),
        migrations.AddField(
            model_name='notificaciontasa',
            name='hora_envio',
            field=models.TimeField(blank=True, help_text='Hora de envío en formato 24h (ej: 08:00)', null=True),
        ),
        migrations.AddField(
            model_name='notificaciontasa',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], help_text='Frecuencia del reporte periódico', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notificaciontasa',
            name='ultima_ejecucion',
            field=models.DateTimeField(blank=True, help_text='Última vez que se envió la notificación periódica', null=True),
        ),
        migrations.AlterField(
            model_name='notificaciontasa',
            name='tipo_alerta',
            field=models.CharField(choices=[('general', 'Cambio General'), ('umbral', 'Alcanzar Umbral'), ('periodica', 'Reporte Periódico')], max_length=10),
        ),
    ]
