# Generated by Django 5.2.4 on 2025-10-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciontasa',
            name='tipo_alerta',
            field=models.CharField(choices=[('general', 'Cambio General'), ('umbral', 'Alcanzar Umbral'), ('transaccion_cancelada', 'Transacción Cancelada')], max_length=25),
        ),
    ]
