# Generated by Django 5.2.4 on 2025-10-15 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_notificaciontasa_tipo_alerta'),

    ]

    operations = [
    ]
