services:
  web:
    container_name: glx-web
    build: .
    #command: /usr/local/bin/python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: glx-db
    image: postgres:17 
    restart: always
    environment:
      - POSTGRES_DB=glex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

volumes:
  postgres_data: