version: '3.8'

services:
  web:
    container_name: glx-web-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: /app/scripts/prod-entrypoint.sh
    volumes:
      - static_volume:/app/staticfiles
      # Si manejas archivos de media, descomenta la siguiente línea
      # - media_volume:/app/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    container_name: glx-nginx
    image: nginx:1.25.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      # Si manejas archivos de media, descomenta la siguiente línea
      # - media_volume:/app/mediafiles
    depends_on:
      - web

  db:
    container_name: glx-db-prod
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/

volumes:
  postgres_data_prod:
  static_volume:
  # Si manejas archivos de media, descomenta la siguiente línea
  # media_volume: