# Generated by Django 5.2.4 on 2025-08-28 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociar_clientes_usuarios', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
