# Generated by Django 5.2.4 on 2025-08-26 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociar_clientes_usuarios', '0001_initial'),
        ('users', '0003_cliente_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='segmento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuarios',
        ),
        migrations.AlterField(
            model_name='asignacioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente'),
        ),
        migrations.AlterField(
            model_name='asignacioncliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Segmento',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
