# Generated by Django 5.2.6 on 2025-12-12 16:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenGananciaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('total_comisiones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Total Comisiones')),
                ('total_spread', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Total Margen')),
                ('total_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Total General')),
                ('cantidad_transacciones', models.IntegerField(default=0, verbose_name='Cantidad de Transacciones')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Resumen de Ganancia Diaria',
                'verbose_name_plural': 'Resúmenes de Ganancias Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ResumenGananciaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('total_comisiones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Total Comisiones')),
                ('total_spread', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Total Margen')),
                ('total_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Total General')),
                ('cantidad_transacciones', models.IntegerField(default=0, verbose_name='Cantidad de Transacciones')),
                ('promedio_diario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Promedio Diario')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Resumen de Ganancia Mensual',
                'verbose_name_plural': 'Resúmenes de Ganancias Mensuales',
                'ordering': ['-año', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='RegistroGanancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ganancia', models.CharField(choices=[('comision', 'Comisión'), ('spread', 'Margen')], max_length=10, verbose_name='Tipo de Ganancia')),
                ('monto_comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ganancia por comisión cobrada al cliente', max_digits=20, verbose_name='Monto de Comisión')),
                ('monto_spread', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ganancia por diferencia entre tasa de compra y venta', max_digits=20, verbose_name='Monto de Margen')),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ganancia total (comisión + spread) en PYG', max_digits=20, verbose_name='Monto Total de Ganancia')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de comisión aplicado', max_digits=5, verbose_name='Porcentaje de Comisión')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_transaccion', models.DateTimeField(help_text='Fecha de la transacción asociada', verbose_name='Fecha de Transacción')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales sobre la ganancia', verbose_name='Notas')),
                ('divisa_referencia', models.ForeignKey(help_text='Divisa extranjera involucrada en la transacción', on_delete=django.db.models.deletion.PROTECT, related_name='ganancias', to='divisas.divisa', verbose_name='Divisa de Referencia')),
            ],
            options={
                'verbose_name': 'Registro de Ganancia',
                'verbose_name_plural': 'Registros de Ganancias',
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
