# Generated by Django 5.2.6 on 2025-12-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ganancias', '0001_initial'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroganancia',
            name='transaccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ganancia', to='transacciones.transaccion', verbose_name='Transacción'),
        ),
        migrations.AlterUniqueTogether(
            name='resumengananciamensual',
            unique_together={('año', 'mes')},
        ),
        migrations.AddIndex(
            model_name='registroganancia',
            index=models.Index(fields=['fecha_transaccion'], name='ganancias_r_fecha_t_8ce50d_idx'),
        ),
        migrations.AddIndex(
            model_name='registroganancia',
            index=models.Index(fields=['tipo_ganancia'], name='ganancias_r_tipo_ga_4fd235_idx'),
        ),
        migrations.AddIndex(
            model_name='registroganancia',
            index=models.Index(fields=['divisa_referencia'], name='ganancias_r_divisa__7350f3_idx'),
        ),
    ]
