# Generated by Django 5.2.7 on 2025-10-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MFAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_login_enabled', models.BooleanField(default=True, help_text='Activar verificación MFA al iniciar sesión', verbose_name='MFA en Login')),
                ('mfa_compra_enabled', models.BooleanField(default=True, help_text='Activar verificación MFA al confirmar una compra', verbose_name='MFA en Compra')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración MFA',
                'verbose_name_plural': 'Configuración MFA',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
