# Generated by Django 5.2.6 on 2025-11-28 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mfa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mfaconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfa_config_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user'], name='mfa_otpcode_user_id_ab4519_idx'),
        ),
    ]
