# Generated by Django 5.2.6 on 2025-10-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfaconfig',
            name='mfa_tauser_enabled',
            field=models.BooleanField(default=True, help_text='Activar verificación MFA al acceder a transacciones en terminales TAUSER', verbose_name='MFA en Tausers'),
        ),
    ]
