# Generated by Django 5.2.6 on 2025-10-14 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_login_enabled', models.BooleanField(default=True, help_text='Activar verificación MFA al iniciar sesión', verbose_name='MFA en Login')),
                ('mfa_compra_enabled', models.BooleanField(default=True, help_text='Activar verificación MFA al confirmar una compra', verbose_name='MFA en Compra')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfa_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración MFA',
                'verbose_name_plural': 'Configuración MFA',
            },
        ),
    ]
