# Generated by Django 5.2.4 on 2025-09-30 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
