# Generated by Django 5.2.6 on 2025-12-12 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Configuración')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Configuración de Transacción',
                'verbose_name_plural': 'Configuraciones de Transacciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('pendiente', 'Pendiente'), ('requiere_confirmacion', 'Requiere Confirmación'), ('pagada', 'Pagada'), ('completado', 'Completado'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], max_length=25, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('requiere_confirmacion', 'Requiere Confirmación'), ('pagada', 'Pagada'), ('completado', 'Completado'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], max_length=25, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Historial de Transacción',
                'verbose_name_plural': 'Historiales de Transacciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaccion', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Transacción')),
                ('tipo_operacion', models.CharField(choices=[('compra', 'Compra de Divisa'), ('venta', 'Venta de Divisa')], max_length=10, verbose_name='Tipo de Operación')),
                ('monto_origen', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Monto Origen')),
                ('monto_destino', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Monto Destino')),
                ('tasa_de_cambio_aplicada', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Tasa de Cambio Aplicada')),
                ('tasa_base', models.DecimalField(blank=True, decimal_places=8, help_text='Tasa de cambio base sin spread ni comisión aplicada', max_digits=20, null=True, verbose_name='Tasa Base (Sin Margen)')),
                ('comision_aplicada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de comisión cobrada al cliente en PYG', max_digits=20, verbose_name='Comisión Aplicada')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de comisión aplicado', max_digits=5, verbose_name='Porcentaje de Comisión')),
                ('margen_spread', models.DecimalField(blank=True, decimal_places=8, help_text='Diferencia entre tasa aplicada y tasa base', max_digits=20, null=True, verbose_name='Margen de Spread')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('requiere_confirmacion', 'Requiere Confirmación'), ('pagada', 'Pagada'), ('completado', 'Completado'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], default='pendiente', max_length=25, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación/Motivo de estado')),
                ('metodo_pago', models.CharField(blank=True, help_text='Campo antiguo - usar medio_pago_datos en su lugar', max_length=100, null=True, verbose_name='Método de Pago (obsoleto)')),
                ('medio_pago_datos', models.JSONField(blank=True, default=dict, help_text='Información del medio utilizado para la operación', null=True, verbose_name='Datos del Medio de Pago/Acreditación')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la transacción', verbose_name='Observaciones')),
                ('tauser_code', models.CharField(blank=True, db_index=True, help_text='Código alfanumérico de 8 caracteres para acceso en terminal', max_length=8, null=True, unique=True, verbose_name='Código Tauser')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
