# Generated by Django 5.2.4 on 2025-09-26 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('divisas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Configuración')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Transacción',
                'verbose_name_plural': 'Configuraciones de Transacciones',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaccion', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Transacción')),
                ('tipo_operacion', models.CharField(choices=[('compra', 'Compra de Divisa'), ('venta', 'Venta de Divisa')], max_length=10, verbose_name='Tipo de Operación')),
                ('monto_origen', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Monto Origen')),
                ('monto_destino', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Monto Destino')),
                ('tasa_de_cambio_aplicada', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Tasa de Cambio Aplicada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada'), ('completado', 'completado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación/Motivo de estado')),
                ('medio_pago_datos', models.JSONField(default=dict, help_text='Información del medio utilizado para la operación', verbose_name='Datos del Medio de Pago/Acreditación')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la transacción', verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='clientes.cliente')),
                ('divisa_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='divisas.divisa')),
                ('divisa_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='divisas.divisa')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_procesadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada'), ('completado', 'completado')], max_length=15, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada'), ('completado', 'completado')], max_length=15, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='transacciones.transaccion')),
            ],
            options={
                'verbose_name': 'Historial de Transacción',
                'verbose_name_plural': 'Historiales de Transacciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['cliente', 'fecha_creacion'], name='transaccion_cliente_4f36ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo_operacion', 'estado'], name='transaccion_tipo_op_29ba41_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['numero_transaccion'], name='transaccion_numero__5b97cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha_creacion'], name='transaccion_fecha_c_da2959_idx'),
        ),
    ]
