# Generated by Django 5.2.6 on 2025-10-03 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('divisas', '0002_initial'),
        ('transacciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontransaccion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialtransaccion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='divisa_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='divisas.divisa'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='divisa_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='divisas.divisa'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='procesado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_procesadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialtransaccion',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='transacciones.transaccion'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['cliente', 'fecha_creacion'], name='transaccion_cliente_4f36ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo_operacion', 'estado'], name='transaccion_tipo_op_29ba41_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['numero_transaccion'], name='transaccion_numero__5b97cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha_creacion'], name='transaccion_fecha_c_da2959_idx'),
        ),
    ]
