# Generated by Django 5.2.4 on 2025-09-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estado_anterior',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada'), ('completado', 'completado')], max_length=15, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estado_nuevo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada'), ('completado', 'completado')], max_length=15, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada'), ('completado', 'completado')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
