# Generated by Django 5.2.6 on 2025-10-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tauser_code',
            field=models.CharField(blank=True, db_index=True, help_text='Código alfanumérico de 8 caracteres para acceso en terminal', max_length=8, null=True, unique=True, verbose_name='Código Tauser'),
        ),
    ]
