# Generated by Django 5.2.4 on 2025-10-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estado_anterior',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], max_length=15, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estado_nuevo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], max_length=15, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='medio_pago_datos',
            field=models.JSONField(blank=True, default=dict, help_text='Información del medio utilizado para la operación', null=True, verbose_name='Datos del Medio de Pago/Acreditación'),
        ),
    ]
