# Generated by Django 5.2.4 on 2025-09-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='observacion',
            field=models.TextField(blank=True, default='', verbose_name='Observación/Motivo de estado'),
        ),
    ]
