# Generated by Django 5.2.6 on 2025-12-07 21:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='comision_aplicada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de comisión cobrada al cliente en PYG', max_digits=20, verbose_name='Comisión Aplicada'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='margen_spread',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Diferencia entre tasa aplicada y tasa base', max_digits=20, null=True, verbose_name='Margen de Spread'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de comisión aplicado', max_digits=5, verbose_name='Porcentaje de Comisión'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tasa_base',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Tasa de cambio base sin spread ni comisión aplicada', max_digits=20, null=True, verbose_name='Tasa Base (Sin Margen)'),
        ),
    ]
