# Generated by Django 5.2.6 on 2025-12-08 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0003_movimientoinventarioterminal_and_more'),
        ('transacciones', '0003_transaccion_comision_aplicada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tauser_deposito',
            field=models.ForeignKey(blank=True, help_text='Terminal TAUSER donde el cliente depositó la divisa (solo ventas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_depositos', to='tauser.terminal'),
        ),
    ]
