# Generated by Django 5.2.4 on 2025-09-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_alter_historialtransaccion_estado_anterior_and_more'),
        ('transacciones', '0003_transaccion_observacion'),
    ]

    operations = [
    ]
