# Generated by Django 5.2.4 on 2025-10-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_alter_historialtransaccion_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estado_anterior',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('completado', 'Completado'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], max_length=15, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estado_nuevo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('completado', 'Completado'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], max_length=15, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('completado', 'Completado'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
