# Generated by Django 5.2.6 on 2025-10-31 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0005_reservadenominacion_and_more'),
        ('transacciones', '0003_transaccion_tauser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tauser_terminal',
            field=models.ForeignKey(blank=True, help_text='Terminal TAUSER donde el cliente debe retirar la divisa (solo compras)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_asignadas', to='tauser.terminal'),
        ),
    ]
