# Generated by Django 5.2.6 on 2025-10-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_transaccion_tauser_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estado_anterior',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('requiere_confirmacion', 'Requiere Confirmación'), ('pagada', 'Pagada'), ('completado', 'Completado'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], max_length=25, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estado_nuevo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('requiere_confirmacion', 'Requiere Confirmación'), ('pagada', 'Pagada'), ('completado', 'Completado'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], max_length=25, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('requiere_confirmacion', 'Requiere Confirmación'), ('pagada', 'Pagada'), ('completado', 'Completado'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], default='pendiente', max_length=25, verbose_name='Estado'),
        ),
    ]
