# Generated by Django 5.2.6 on 2025-10-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_alter_historialtransaccion_estado_anterior_and_more'),
    ]

    operations = [
        # Modificar el campo metodo_pago existente en la BD para que sea nullable
        migrations.RunSQL(
            sql='ALTER TABLE transacciones_transaccion ALTER COLUMN metodo_pago DROP NOT NULL;',
            reverse_sql='ALTER TABLE transacciones_transaccion ALTER COLUMN metodo_pago SET NOT NULL;',
        ),
    ]
