# Generated by Django 5.2.6 on 2025-09-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del medio')),
                ('tipo', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('BILLETERA', 'Billetera Digital'), ('CHEQUE', 'Cheque')], default='TARJETA', max_length=20, verbose_name='Tipo de medio')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión (%)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['is_active'], name='medios_pago_is_acti_6a6425_idx'), models.Index(fields=['tipo'], name='medios_pago_tipo_919fb4_idx')],
            },
        ),
    ]
