# Generated by Django 5.2.6 on 2025-09-05 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del medio')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión del 0 al 100', max_digits=5, verbose_name='Comisión (%)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['is_active'], name='medios_pago_is_acti_6a6425_idx'), models.Index(fields=['nombre'], name='medios_pago_nombre_c380e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampoMedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=100, verbose_name='Nombre del campo')),
                ('tipo_dato', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('FECHA', 'Fecha'), ('EMAIL', 'Email'), ('TELEFONO', 'Teléfono'), ('URL', 'URL')], max_length=10, verbose_name='Tipo de Dato')),
                ('is_required', models.BooleanField(default=True, verbose_name='Requerido')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('medio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='medios_pago.mediodepago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Campo de Medio de Pago',
                'verbose_name_plural': 'Campos de Medios de Pago',
                'ordering': ['orden', 'id'],
                'unique_together': {('medio_de_pago', 'nombre_campo')},
            },
        ),
    ]
