# Generated by Django 5.2.6 on 2025-10-01 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del medio')),
                ('template_usado', models.CharField(blank=True, help_text='Template predefinido o personalizado usado como base', max_length=50, verbose_name='Template utilizado')),
                ('tipo_medio', models.CharField(blank=True, choices=[('stripe', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('bank_local', 'Transferencia Bancaria Local'), ('bank_international', 'Transferencia Bancaria Internacional'), ('bitcoin', 'Criptomonedas (Bitcoin, Ethereum)'), ('billetera_electronica', 'Billetera Electrónica'), ('efectivo', 'Pago en Efectivo')], help_text='Tipo de procesador que manejará este medio de pago', max_length=50, null=True, verbose_name='Tipo de Medio de Pago')),
                ('comision_porcentaje', models.DecimalField(decimal_places=3, default=0, help_text='Porcentaje de comisión del 0 al 100', max_digits=6, verbose_name='Comisión (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del template')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('fields_config', models.JSONField(default=list, verbose_name='Configuración de campos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Template de Pago',
                'verbose_name_plural': 'Templates de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampoMedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=100, verbose_name='Nombre del campo')),
                ('campo_api', models.CharField(choices=[('card_number', 'Número de tarjeta'), ('exp_month', 'Mes de vencimiento'), ('exp_year', 'Año de vencimiento'), ('cvc', 'Código de seguridad'), ('cardholder_name', 'Nombre en la tarjeta'), ('paypal_email', 'Email de PayPal'), ('account_number', 'Número de cuenta'), ('bank_name', 'Entidad'), ('account_holder', 'Titular de la cuenta'), ('routing_number', 'Código de routing'), ('swift_code', 'Código SWIFT'), ('cbu_cvu', 'CBU/CVU'), ('ruc', 'RUC'), ('email', 'Email'), ('phone', 'Teléfono'), ('description', 'Descripción'), ('wallet_address', 'Dirección de billetera'), ('network', 'Red'), ('wallet_phone', 'Teléfono de billetera'), ('wallet_email', 'Email de billetera'), ('wallet_user_id', 'ID de usuario'), ('document_number', 'Número de documento')], help_text='Campo estandarizado para la API', max_length=100, verbose_name='Campo API')),
                ('tipo_dato', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('FECHA', 'Fecha'), ('EMAIL', 'Email'), ('TELEFONO', 'Teléfono'), ('URL', 'URL')], max_length=10, verbose_name='Tipo de Dato')),
                ('is_required', models.BooleanField(default=True, verbose_name='Requerido')),
                ('descripcion', models.TextField(blank=True, help_text='Ayuda para el usuario', verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('medio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='medios_pago.mediodepago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Campo de Medio de Pago',
                'verbose_name_plural': 'Campos de Medios de Pago',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
