# Generated by Django 5.2.6 on 2025-09-05 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediodepago',
            name='medios_pago_is_acti_6a6425_idx',
        ),
        migrations.RemoveIndex(
            model_name='mediodepago',
            name='medios_pago_nombre_c380e2_idx',
        ),
        migrations.AddField(
            model_name='campomediodepago',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campomediodepago',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campomediodepago',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en'),
        ),
        migrations.AddField(
            model_name='mediodepago',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminado en'),
        ),
    ]
