# Generated by Django 5.2.6 on 2025-09-04 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoMedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del campo (clave)')),
                ('etiqueta', models.CharField(blank=True, max_length=150, verbose_name='Etiqueta visible')),
                ('tipo_dato', models.CharField(choices=[('string', 'Cadena'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('email', 'Email')], default='string', max_length=20, verbose_name='Tipo de dato')),
                ('requerido', models.BooleanField(default=False, verbose_name='Requerido')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('medio', models.ForeignKey(help_text='Medio de pago al que pertenece este campo', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='medios_pago.mediodepago')),
            ],
            options={
                'verbose_name': 'Campo de Medio de Pago',
                'verbose_name_plural': 'Campos de Medios de Pago',
                'ordering': ['medio', 'orden', 'nombre'],
                'unique_together': {('medio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='InstanciaMedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='medios_pago.mediodepago')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medios_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instancia de Medio de Pago',
                'verbose_name_plural': 'Instancias de Medios de Pago',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ValorCampoInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medios_pago.campomediopago')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='medios_pago.instanciamediopago')),
            ],
            options={
                'verbose_name': 'Valor de Campo de Instancia',
                'verbose_name_plural': 'Valores de Campos de Instancia',
                'unique_together': {('instancia', 'campo')},
            },
        ),
    ]
