# Generated by Django 5.2.6 on 2025-10-03 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medios_pago', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='mediodepago',
            name='custom_template',
            field=models.ForeignKey(blank=True, help_text='Template personalizado usado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medios_pago.paymenttemplate', verbose_name='Template personalizado'),
        ),
        migrations.AlterUniqueTogether(
            name='campomediodepago',
            unique_together={('medio_de_pago', 'campo_api')},
        ),
    ]
