# Generated by Django 5.2.6 on 2025-09-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0002_remove_mediodepago_medios_pago_is_acti_6a6425_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campomediodepago',
            unique_together=set(),
        ),
    ]
