# Generated by Django 5.2.6 on 2025-10-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='tipo_medio',
            field=models.CharField(blank=True, choices=[('stripe', 'Tarjeta de Crédito/Débito (Stripe)'), ('tarjeta_local', 'Tarjeta de Crédito/Débito (Local)'), ('paypal', 'PayPal'), ('bank_local', 'Transferencia Bancaria Local'), ('bank_international', 'Transferencia Bancaria Internacional'), ('bitcoin', 'Criptomonedas (Bitcoin, Ethereum)'), ('billetera_electronica', 'Billetera Electrónica'), ('efectivo', 'Pago en Efectivo')], help_text='Tipo de procesador que manejará este medio de pago', max_length=50, null=True, verbose_name='Tipo de Medio de Pago'),
        ),
    ]
