# Generated by Django 5.2.6 on 2025-09-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0003_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Porcentaje de comisión del 0 al 100', max_digits=6, verbose_name='Comisión (%)'),
        ),
    ]
