# Generated by Django 5.2.6 on 2025-09-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0004_alter_mediodepago_comision_porcentaje'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campomediodepago',
            unique_together={('medio_de_pago', 'nombre_campo')},
        ),
        migrations.RemoveField(
            model_name='mediodepago',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.RemoveField(
            model_name='campomediodepago',
            name='deleted_at',
        ),
    ]
