# Generated by Django 5.2.6 on 2025-09-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0006_alter_campomediodepago_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomediodepago',
            name='campo_api',
            field=models.CharField(choices=[('card_number', 'Número de tarjeta'), ('exp_month', 'Mes de vencimiento'), ('exp_year', 'Año de vencimiento'), ('cvc', 'Código de seguridad'), ('cardholder_name', 'Nombre en la tarjeta'), ('paypal_email', 'Email de PayPal'), ('account_number', 'Número de cuenta'), ('bank_name', 'Nombre del banco'), ('account_holder', 'Titular de la cuenta'), ('routing_number', 'Código de routing'), ('swift_code', 'Código SWIFT'), ('cbu_cvu', 'CBU/CVU'), ('email', 'Email'), ('phone', 'Teléfono'), ('amount', 'Monto'), ('currency', 'Moneda'), ('description', 'Descripción'), ('wallet_address', 'Dirección de billetera'), ('network', 'Red')], help_text='Campo estandarizado para la API', max_length=100, verbose_name='Campo API'),
        ),
    ]
