# Generated by Django 5.2.6 on 2025-09-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0007_alter_campomediodepago_campo_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomediodepago',
            name='campo_api',
            field=models.CharField(choices=[('card_number', 'NÃºmero de tarjeta'), ('exp_month', 'Mes de vencimiento'), ('exp_year', 'AÃ±o de vencimiento'), ('cvc', 'CÃ³digo de seguridad'), ('cardholder_name', 'Nombre en la tarjeta'), ('paypal_email', 'Email de PayPal'), ('account_number', 'NÃºmero de cuenta'), ('bank_name', 'Nombre del banco'), ('account_holder', 'Titular de la cuenta'), ('routing_number', 'CÃ³digo de routing'), ('swift_code', 'CÃ³digo SWIFT'), ('cbu_cvu', 'CBU/CVU'), ('email', 'Email'), ('phone', 'TelÃ©fono'), ('amount', 'Monto'), ('currency', 'Moneda'), ('description', 'DescripciÃ³n'), ('wallet_address', 'DirecciÃ³n de billetera'), ('network', 'Red')], help_text='Campo estandarizado para la API', max_length=100, verbose_name='Campo API'),
        ),
        migrations.AlterField(
            model_name='campomediodepago',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Ayuda para el usuario', verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='campomediodepago',
            name='tipo_dato',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'NÃºmero'), ('FECHA', 'Fecha'), ('EMAIL', 'Email'), ('TELEFONO', 'TelÃ©fono'), ('URL', 'URL')], max_length=10, verbose_name='Tipo de Dato'),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Porcentaje de comisiÃ³n del 0 al 100', max_digits=6, verbose_name='ComisiÃ³n (%)'),
        ),
    ]
