# Generated by Django 5.2.6 on 2025-09-24 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0008_alter_campomediodepago_campo_api_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomediodepago',
            name='campo_api',
            field=models.CharField(choices=[('card_number', 'Número de tarjeta'), ('exp_month', 'Mes de vencimiento'), ('exp_year', 'Año de vencimiento'), ('cvc', 'Código de seguridad'), ('cardholder_name', 'Nombre en la tarjeta'), ('paypal_email', 'Email de PayPal'), ('account_number', 'Número de cuenta'), ('bank_name', 'Nombre del banco'), ('account_holder', 'Titular de la cuenta'), ('routing_number', 'Código de routing'), ('swift_code', 'Código SWIFT'), ('cbu_cvu', 'CBU/CVU'), ('email', 'Email'), ('phone', 'Teléfono'), ('amount', 'Monto'), ('currency', 'Moneda'), ('description', 'Descripción'), ('wallet_address', 'Dirección de billetera'), ('network', 'Red')], help_text='Campo estandarizado para la API', max_length=100, verbose_name='Campo API'),
        ),
        migrations.AlterField(
            model_name='campomediodepago',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Ayuda para el usuario', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='campomediodepago',
            name='tipo_dato',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('FECHA', 'Fecha'), ('EMAIL', 'Email'), ('TELEFONO', 'Teléfono'), ('URL', 'URL')], max_length=10, verbose_name='Tipo de Dato'),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Porcentaje de comisión del 0 al 100', max_digits=6, verbose_name='Comisión (%)'),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='template_usado',
            field=models.CharField(blank=True, help_text='Template predefinido o personalizado usado como base', max_length=50, verbose_name='Template utilizado'),
        ),
        migrations.CreateModel(
            name='PaymentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del template')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('fields_config', models.JSONField(default=list, verbose_name='Configuración de campos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Template de Pago',
                'verbose_name_plural': 'Templates de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mediodepago',
            name='custom_template',
            field=models.ForeignKey(blank=True, help_text='Template personalizado usado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medios_pago.paymenttemplate', verbose_name='Template personalizado'),
        ),
    ]
