# Generated by Django 5.2.6 on 2025-09-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0009_alter_campomediodepago_campo_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediodepago',
            name='tipo_medio',
            field=models.CharField(blank=True, choices=[('stripe', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('bank_local', 'Transferencia Bancaria Local'), ('bank_international', 'Transferencia Bancaria Internacional'), ('bitcoin', 'Criptomonedas (Bitcoin, Ethereum)'), ('efectivo', 'Pago en Efectivo')], help_text='Tipo de procesador que manejará este medio de pago', max_length=50, null=True, verbose_name='Tipo de Medio de Pago'),
        ),
    ]
