# Generated by Django 5.2.6 on 2025-09-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0010_mediodepago_tipo_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campomediodepago',
            name='campo_api',
            field=models.CharField(choices=[('card_number', 'Número de tarjeta'), ('exp_month', 'Mes de vencimiento'), ('exp_year', 'Año de vencimiento'), ('cvc', 'Código de seguridad'), ('cardholder_name', 'Nombre en la tarjeta'), ('paypal_email', 'Email de PayPal'), ('account_number', 'Número de cuenta'), ('bank_name', 'Entidad'), ('account_holder', 'Titular de la cuenta'), ('routing_number', 'Código de routing'), ('swift_code', 'Código SWIFT'), ('cbu_cvu', 'CBU/CVU'), ('ruc', 'RUC'), ('email', 'Email'), ('phone', 'Teléfono'), ('description', 'Descripción'), ('wallet_address', 'Dirección de billetera'), ('network', 'Red'), ('wallet_phone', 'Teléfono de billetera'), ('wallet_email', 'Email de billetera'), ('wallet_user_id', 'ID de usuario'), ('document_number', 'Número de documento')], help_text='Campo estandarizado para la API', max_length=100, verbose_name='Campo API'),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='tipo_medio',
            field=models.CharField(blank=True, choices=[('stripe', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('bank_local', 'Transferencia Bancaria Local'), ('bank_international', 'Transferencia Bancaria Internacional'), ('bitcoin', 'Criptomonedas (Bitcoin, Ethereum)'), ('billetera_electronica', 'Billetera Electrónica'), ('efectivo', 'Pago en Efectivo')], help_text='Tipo de procesador que manejará este medio de pago', max_length=50, null=True, verbose_name='Tipo de Medio de Pago'),
        ),
    ]
