# Generated by Django 5.2.6 on 2025-10-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('compra', 'Compra de Divisa'), ('venta', 'Venta de Divisa')], default='compra', max_length=10, verbose_name='Tipo de Transacción')),
                ('payment_intent_id', models.CharField(db_index=True, help_text='ID del Payment Intent en Stripe', max_length=255, unique=True, verbose_name='Payment Intent ID')),
                ('charge_id', models.CharField(blank=True, help_text='ID del cargo en Stripe (si aplica)', max_length=255, null=True, verbose_name='Charge ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la transacción en guaraníes', max_digits=15, verbose_name='Monto')),
                ('currency', models.CharField(default='PYG', help_text='Código de moneda ISO', max_length=3, verbose_name='Moneda')),
                ('divisa_code', models.CharField(blank=True, help_text='Código de la divisa operada (USD, EUR, etc.)', max_length=10, verbose_name='Código de Divisa')),
                ('monto_divisa', models.DecimalField(blank=True, decimal_places=2, help_text='Monto en la divisa extranjera', max_digits=15, null=True, verbose_name='Monto en Divisa')),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=6, help_text='Tasa de cambio aplicada', max_digits=15, null=True, verbose_name='Tasa de Cambio')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('succeeded', 'Exitosa'), ('failed', 'Fallida'), ('canceled', 'Cancelada'), ('requires_action', 'Requiere Acción'), ('refunded', 'Reembolsada')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('stripe_response', models.JSONField(blank=True, help_text='Respuesta completa de la API de Stripe', null=True, verbose_name='Respuesta de Stripe')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la transacción falló', null=True, verbose_name='Mensaje de Error')),
                ('card_last4', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4, verbose_name='Últimos 4 dígitos')),
                ('card_brand', models.CharField(blank=True, help_text='Marca de la tarjeta (Visa, Mastercard, etc.)', max_length=50, verbose_name='Marca de Tarjeta')),
                ('cliente_medio_pago_id', models.IntegerField(blank=True, help_text='ID del ClienteMedioDePago usado', null=True, verbose_name='ID Medio de Pago Cliente')),
                ('metadata', models.JSONField(blank=True, help_text='Información adicional de la operación', null=True, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del Cliente')),
            ],
            options={
                'verbose_name': 'Transacción Stripe',
                'verbose_name_plural': 'Transacciones Stripe',
                'ordering': ['-created_at'],
            },
        ),
    ]
