# Generated by Django 5.2.6 on 2025-10-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripetransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('succeeded', 'Exitosa'), ('failed', 'Fallida'), ('canceled', 'Cancelada'), ('requires_action', 'Requiere Acción'), ('refunded', 'Reembolsada')], db_index=True, default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
