# Generated by Django 5.2.4 on 2025-10-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stripe_payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddIndex(
            model_name='stripetransaction',
            index=models.Index(fields=['-created_at'], name='stripe_paym_created_d89112_idx'),
        ),
        migrations.AddIndex(
            model_name='stripetransaction',
            index=models.Index(fields=['cliente', '-created_at'], name='stripe_paym_cliente_a2a0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='stripetransaction',
            index=models.Index(fields=['status'], name='stripe_paym_status_a2fabd_idx'),
        ),
    ]
