# Generated by Django 5.2.6 on 2025-10-03 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('clientes', 'Gestión de Clientes'), ('divisas', 'Operaciones de Divisas'), ('medios_pago', 'Medios de Pago'), ('transacciones', 'Transacciones'), ('usuarios', 'Gestión de Usuarios'), ('reportes', 'Reportes y Exportaciones'), ('configuracion', 'Configuración del Sistema')], help_text='Módulo funcional al que pertenece', max_length=50)),
                ('descripcion_detallada', models.TextField(help_text='Explicación clara de qué permite hacer este permiso')),
                ('ejemplo_uso', models.TextField(blank=True, help_text='Ejemplo concreto de uso del permiso')),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo - Solo lectura'), ('medio', 'Medio - Modificación de datos'), ('alto', 'Alto - Operaciones críticas'), ('critico', 'Crítico - Administración del sistema')], default='medio', help_text='Nivel de riesgo de seguridad', max_length=20)),
                ('orden', models.IntegerField(default=0, help_text='Orden para mostrar en interfaz')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metadata de Permiso',
                'verbose_name_plural': 'Metadata de Permisos',
                'ordering': ['modulo', 'orden', 'permission__name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('add', 'Permiso agregado'), ('remove', 'Permiso removido'), ('update', 'Actualización masiva')], max_length=20)),
                ('permisos_modificados', models.JSONField(default=list, help_text='Lista de IDs de permisos modificados')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_changes', to='auth.group')),
            ],
            options={
                'verbose_name': 'Log de Cambio de Permisos',
                'verbose_name_plural': 'Logs de Cambios de Permisos',
                'ordering': ['-fecha'],
            },
        ),
    ]
