# Generated by Django 5.2.6 on 2025-10-03 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionchangelog',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionmetadata',
            name='permission',
            field=models.OneToOneField(help_text='Permiso de Django asociado', on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='rolestatus',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='auth.group'),
        ),
    ]
