# roles/management/commands/permissions_defs/clientes.py

PERMISOS_CLIENTES = [
    # Visualización
    {
        'app_label': 'clientes',
        'model': 'cliente',
        'codename': 'view_assigned_clientes',
        'name': 'Puede ver clientes asignados',
        'modulo': 'clientes',
        'descripcion': 'Permite ver únicamente los clientes que están asignados al usuario',
        'ejemplo': 'Un operador puede ver los datos de sus 5 clientes asignados pero no de otros',
        'nivel_riesgo': 'bajo',
        'orden': 1,
    },
    {
        'app_label': 'clientes',
        'model': 'cliente',
        'codename': 'view_all_clientes',
        'name': 'Puede ver todos los clientes',
        'modulo': 'clientes',
        'descripcion': 'Permite ver TODOS los clientes del sistema sin restricción de asignación',
        'ejemplo': 'Un administrador puede ver cualquier cliente del sistema',
        'nivel_riesgo': 'medio',
        'orden': 2,
    },
    
    # Gestión de asignaciones
    {
        'app_label': 'clientes',
        'model': 'asignacioncliente',
        'codename': 'manage_cliente_assignment',
        'name': 'Puede asignar clientes a operadores',
        'modulo': 'clientes',
        'descripcion': 'Permite asociar y desasociar clientes con operadores del sistema',
        'ejemplo': 'Un supervisor puede asignar nuevos clientes a sus operadores',
        'nivel_riesgo': 'alto',
        'orden': 3,
    },
    
    # Límites
    {
        'app_label': 'clientes',
        'model': 'limitediario',
        'codename': 'manage_limits',
        'name': 'Puede modificar límites diarios y mensuales',
        'modulo': 'clientes',
        'descripcion': 'Permite crear y modificar los límites de operación diarios y mensuales del sistema',
        'ejemplo': 'Un administrador puede aumentar el límite diario de operaciones de $10,000 a $15,000',
        'nivel_riesgo': 'critico',
        'orden': 4,
    },
    {
        'app_label': 'clientes',
        'model': 'limitediario',
        'codename': 'view_limites_operacion',
        'name': 'Puede ver límites diarios y mensuales',
        'modulo': 'clientes',
        'descripcion': 'Permite consultar los límites máximos configurados para las operaciones de los clientes.',
        'ejemplo': 'Revisar el límite mensual vigente antes de autorizar una operación.',
        'nivel_riesgo': 'bajo',
        'orden': 50,
    },
    {
        'app_label': 'clientes',
        'model': 'limitediario',
        'codename': 'manage_limites_operacion',
        'name': 'Puede administrar límites diarios y mensuales',
        'modulo': 'clientes',
        'descripcion': 'Autoriza la creación y modificación de límites diarios y mensuales aplicables a los clientes.',
        'ejemplo': 'Actualizar el límite diario para el segmento corporativo.',
        'nivel_riesgo': 'medio',
        'orden': 55,
    },
    
    # Medios de pago
    {
        'app_label': 'clientes',
        'model': 'clientemediodepago',
        'codename': 'manage_medios_pago',
        'name': 'Puede gestionar medios de pago del cliente',
        'modulo': 'medios_pago',
        'descripcion': 'Crear, editar o eliminar medios de pago asociados a un cliente asignado.',
        'ejemplo': 'Agregar tarjeta VISA para el cliente Juan Pérez.',
        'nivel_riesgo': 'medio',
        'orden': 40,
    },
    {
        'app_label': 'clientes',
        'model': 'clientemediodepago',
        'codename': 'view_medios_pago',
        'name': 'Puede ver medios de pago del cliente',
        'modulo': 'medios_pago',
        'descripcion': 'Consultar los medios de pago habilitados para un cliente asignado.',
        'ejemplo': 'Listar los alias bancarios disponibles para la empresa ACME.',
        'nivel_riesgo': 'bajo',
        'orden': 45,
    },
    
    # Exportación
    {
        'app_label': 'clientes',
        'model': 'cliente',
        'codename': 'export_cliente_data',
        'name': 'Puede exportar datos de clientes',
        'modulo': 'reportes',
        'descripcion': 'Permite exportar información de clientes en formatos CSV/Excel',
        'ejemplo': 'Un contador puede exportar todos los clientes con sus datos fiscales',
        'nivel_riesgo': 'medio',
        'orden': 1,
    },
    {
        'app_label': 'clientes',
        'model': 'descuento',
        'codename': 'view_descuentos_segmento',
        'name': 'Puede ver descuentos por segmento',
        'modulo': 'clientes',
        'descripcion': 'Permite consultar los descuentos configurados para cada segmento de clientes.',
        'ejemplo': 'Ver el porcentaje de descuento aplicado al segmento VIP.',
        'nivel_riesgo': 'bajo',
        'orden': 60,
    },
    {
        'app_label': 'clientes',
        'model': 'descuento',
        'codename': 'manage_descuentos_segmento',
        'name': 'Puede administrar descuentos por segmento',
        'modulo': 'clientes',
        'descripcion': 'Autoriza la creación y modificación de descuentos asociados a segmentos de clientes.',
        'ejemplo': 'Actualizar el descuento del segmento emprendedores.',
        'nivel_riesgo': 'medio',
        'orden': 65,
    },
    {
        'app_label': 'clientes',
        'model': 'historialdescuentos',
        'codename': 'view_historial_descuentos',
        'name': 'Puede ver el historial de descuentos',
        'modulo': 'clientes',
        'descripcion': 'Permite auditar los cambios realizados sobre los descuentos de segmentos.',
        'ejemplo': 'Revisar quién modificó el descuento del segmento PyME la semana pasada.',
        'nivel_riesgo': 'bajo',
        'orden': 70,
    },
]