# roles/management/commands/permissions_defs/transacciones.py

PERMISOS_TRANSACCIONES = [
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'view_transacciones_asignadas',
        'name': 'Puede ver transacciones asignadas',
        'modulo': 'transacciones',
        'descripcion': 'Permite consultar solo las transacciones asociadas a los clientes asignados al usuario.',
        'ejemplo': 'Ver las operaciones realizadas por el cliente Metalúrgica SA.',
        'nivel_riesgo': 'bajo',
        'orden': 10,
    },
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'view_transacciones_globales',
        'name': 'Puede ver todas las transacciones',
        'modulo': 'transacciones',
        'descripcion': 'Autoriza el acceso al listado completo de transacciones registradas en el sistema.',
        'ejemplo': 'Auditar las transacciones del mes sin restricción por operador.',
        'nivel_riesgo': 'medio',
        'orden': 20,
    },
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'manage_reversiones_transacciones',
        'name': 'Puede gestionar reversiones de transacciones',
        'modulo': 'transacciones',
        'descripcion': 'Habilita la solicitud y aprobación de reversiones sobre transacciones existentes.',
        'ejemplo': 'Iniciar la reversión de una compra de divisas cargada por error.',
        'nivel_riesgo': 'critico',
        'orden': 30,
    },
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'export_transacciones',
        'name': 'Puede exportar transacciones',
        'modulo': 'transacciones',
        'descripcion': 'Permite generar archivos de exportación con el historial de transacciones.',
        'ejemplo': 'Descargar un CSV con las transacciones del último trimestre.',
        'nivel_riesgo': 'medio',
        'orden': 40,
    },
]