"""
Definiciones de permisos personalizados para la app 'transacciones'.
"""

PERMISOS_TRANSACCIONES = [
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'view_transacciones_asignadas',
        'name': 'Puede ver transacciones de clientes asignados',
        'modulo': 'transacciones',
        'descripcion': 'Permite visualizar el historial de transacciones de sus clientes asignados',
        'ejemplo': 'Un operador puede consultar las transacciones de sus clientes',
        'nivel_riesgo': 'bajo',
        'orden': 10,
        'categoria': 'consulta_transacciones',
        'requiere_auditoria': False,
    },
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'view_transacciones_globales',
        'name': 'Puede ver TODAS las transacciones del sistema',
        'modulo': 'transacciones',
        'descripcion': 'Permite visualizar el historial completo de transacciones sin restricciones',
        'ejemplo': 'Un administrador puede auditar todas las transacciones realizadas',
        'nivel_riesgo': 'medio',
        'orden': 20,
        'categoria': 'auditoria_transacciones',
        'requiere_auditoria': True,
    },
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'manage_estados_transacciones',
        'name': 'Puede cambiar estados de transacciones',
        'modulo': 'transacciones',
        'descripcion': 'Permite modificar el estado de transacciones (pendiente → pagada → completada)',
        'ejemplo': 'Un operador puede marcar una transacción como pagada tras verificar el pago',
        'nivel_riesgo': 'alto',
        'orden': 30,
        'categoria': 'gestion_transacciones',
        'requiere_auditoria': True,
    },
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'manage_reversiones_transacciones',
        'name': 'Puede revertir/anular transacciones',
        'modulo': 'transacciones',
        'descripcion': 'Permite anular o revertir transacciones completadas. Solo para supervisores/admin.',
        'ejemplo': 'Un supervisor puede anular una transacción errónea y devolver fondos',
        'nivel_riesgo': 'critico',
        'orden': 40,
        'categoria': 'gestion_critica',
        'requiere_auditoria': True,
    },
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'cancel_propias_transacciones',
        'name': 'Puede cancelar sus propias transacciones pendientes',
        'modulo': 'transacciones',
        'descripcion': 'Permite que clientes cancelen transacciones en estado pendiente antes del pago',
        'ejemplo': 'Un cliente puede cancelar una operación antes de completar el pago',
        'nivel_riesgo': 'bajo',
        'orden': 50,
        'categoria': 'gestion_cliente',
        'requiere_auditoria': False,
    },
    {
        'app_label': 'transacciones',
        'model': 'historialtransaccion',
        'codename': 'view_historial_transacciones',
        'name': 'Puede ver historial de cambios de transacciones',
        'modulo': 'transacciones',
        'descripcion': 'Permite visualizar el log de auditoría de cambios en transacciones',
        'ejemplo': 'Un auditor puede revisar quién modificó el estado de una transacción y cuándo',
        'nivel_riesgo': 'medio',
        'orden': 60,
        'categoria': 'auditoria_transacciones',
        'requiere_auditoria': False,
    },
    {
        'app_label': 'transacciones',
        'model': 'transaccion',
        'codename': 'export_transacciones',
        'name': 'Puede exportar transacciones a CSV/Excel',
        'modulo': 'transacciones',
        'descripcion': 'Permite descargar reportes de transacciones en formato CSV o Excel',
        'ejemplo': 'Un administrador puede exportar todas las transacciones del mes para contabilidad',
        'nivel_riesgo': 'medio',
        'orden': 70,
        'categoria': 'reportes',
        'requiere_auditoria': True,
    },
]