"""
Definiciones de permisos personalizados para la app 'users'.
"""

PERMISOS_USUARIOS = [
    {
        'app_label': 'users',
        'model': 'customuser',
        'codename': 'manage_usuarios',
        'name': 'Puede gestionar usuarios del sistema',
        'modulo': 'usuarios',
        'descripcion': 'Permite crear, editar y eliminar cuentas de usuario. Solo para administradores.',
        'ejemplo': 'Un administrador puede crear una cuenta para un nuevo operador',
        'nivel_riesgo': 'critico',
        'orden': 10,
        'categoria': 'gestion_usuarios',
        'requiere_auditoria': True,
    },
    {
        'app_label': 'users',
        'model': 'customuser',
        'codename': 'view_all_usuarios',
        'name': 'Puede ver todos los usuarios',
        'modulo': 'usuarios',
        'descripcion': 'Permite visualizar la lista completa de usuarios del sistema con sus datos',
        'ejemplo': 'Un administrador puede consultar todos los usuarios registrados',
        'nivel_riesgo': 'medio',
        'orden': 20,
        'categoria': 'consulta_usuarios',
        'requiere_auditoria': False,
    },
    {
        'app_label': 'users',
        'model': 'customuser',
        'codename': 'manage_usuario_roles',
        'name': 'Puede asignar roles a usuarios',
        'modulo': 'usuarios',
        'descripcion': 'Permite agregar o quitar usuarios de grupos (admin, operador, cliente)',
        'ejemplo': 'Un administrador puede promover un operador a supervisor',
        'nivel_riesgo': 'critico',
        'orden': 30,
        'categoria': 'gestion_roles',
        'requiere_auditoria': True,
    },
    {
        'app_label': 'users',
        'model': 'customuser',
        'codename': 'activate_deactivate_usuarios',
        'name': 'Puede activar/desactivar usuarios',
        'modulo': 'usuarios',
        'descripcion': 'Permite habilitar o deshabilitar cuentas de usuario sin eliminarlas',
        'ejemplo': 'Un administrador puede desactivar temporalmente la cuenta de un operador',
        'nivel_riesgo': 'alto',
        'orden': 40,
        'categoria': 'gestion_usuarios',
        'requiere_auditoria': True,
    },
    {
        'app_label': 'users',
        'model': 'customuser',
        'codename': 'reset_usuario_password',
        'name': 'Puede resetear contraseñas de usuarios',
        'modulo': 'usuarios',
        'descripcion': 'Permite restablecer la contraseña de otros usuarios',
        'ejemplo': 'Un administrador puede resetear la contraseña de un operador que la olvidó',
        'nivel_riesgo': 'alto',
        'orden': 50,
        'categoria': 'gestion_usuarios',
        'requiere_auditoria': True,
    },
]