# roles/management/commands/permissions_defs/usuarios.py

PERMISOS_USUARIOS = [
    {
        'app_label': 'users',
        'model': 'customuser',
        'codename': 'view_usuarios',
        'name': 'Puede ver usuarios',
        'modulo': 'usuarios',
        'descripcion': 'Permite acceder al listado y detalle de usuarios registrados.',
        'ejemplo': 'Consultar los datos del usuario operador01.',
        'nivel_riesgo': 'bajo',
        'orden': 10,
    },
    {
        'app_label': 'users',
        'model': 'customuser',
        'codename': 'manage_usuarios',
        'name': 'Puede administrar usuarios',
        'modulo': 'usuarios',
        'descripcion': 'Autoriza la creación y edición de usuarios internos y clientes.',
        'ejemplo': 'Registrar un nuevo operador y definir sus datos de contacto.',
        'nivel_riesgo': 'alto',
        'orden': 20,
    },
    {
        'app_label': 'auth',
        'model': 'group',
        'codename': 'assign_roles_usuarios',
        'name': 'Puede asignar roles a usuarios',
        'modulo': 'usuarios',
        'descripcion': 'Habilita la asignación y revocación de roles y grupos de permisos.',
        'ejemplo': 'Agregar el rol Supervisor al usuario maria.gomez.',
        'nivel_riesgo': 'critico',
        'orden': 30,
    },
    {
        'app_label': 'users',
        'model': 'customuser',
        'codename': 'reset_password_usuarios',
        'name': 'Puede resetear contraseñas de usuarios',
        'modulo': 'usuarios',
        'descripcion': 'Permite iniciar el proceso de restablecimiento de contraseñas para otros usuarios.',
        'ejemplo': 'Forzar el reseteo de contraseña del usuario operador03.',
        'nivel_riesgo': 'alto',
        'orden': 40,
    },
]