# Generated by Django 5.2.4 on 2025-09-30 02:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medios_pago', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimiteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha a la que aplica el límite', unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('inicio_vigencia', models.DateTimeField(help_text='Fecha y hora en que entra en vigencia el límite')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LimiteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Se guarda como el primer día del mes', unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('inicio_vigencia', models.DateTimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-mes'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Cliente',
                'verbose_name_plural': 'Asignaciones de Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('tipo_cliente', models.CharField(default='minorista', max_length=50, verbose_name='Tipo de Cliente')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('usuarios', models.ManyToManyField(through='clientes.AsignacionCliente', to=settings.AUTH_USER_MODEL)),
                ('segmento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.segmento', verbose_name='Segmento')),
            ],
        ),
        migrations.AddField(
            model_name='asignacioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.CreateModel(
            name='ClienteMedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_campos', models.JSONField(default=dict, help_text='Datos dinámicos según los campos del medio de pago')),
                ('es_activo', models.BooleanField(default=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es el medio de pago principal del cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medios_pago_creados', to=settings.AUTH_USER_MODEL)),
                ('medio_de_pago', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='medios_pago.mediodepago')),
            ],
            options={
                'verbose_name': 'Medio de Pago del Cliente',
                'verbose_name_plural': 'Medios de Pago de Clientes',
                'ordering': ['-es_principal', '-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('segmento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.segmento', verbose_name='Segmento de Cliente')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Descuento aplicado (%)')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='HistorialClienteMedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado'), ('DESACTIVADO', 'Desactivado'), ('ACTIVADO', 'Activado')], max_length=20)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente_medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.clientemediodepago')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Medio de Pago',
                'verbose_name_plural': 'Historial de Medios de Pago',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='asignacioncliente',
            unique_together={('usuario', 'cliente')},
        ),
        migrations.CreateModel(
            name='HistorialDescuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento_anterior', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento anterior (%)')),
                ('porcentaje_descuento_nuevo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nuevo descuento (%)')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.descuento', verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Historial de Descuento',
                'verbose_name_plural': 'Historial de Descuentos',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
