# Generated by Django 5.2.5 on 2025-08-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('tipo_cliente', models.CharField(default='minorista', max_length=50, verbose_name='Tipo de Cliente')),
            ],
        ),
    ]
