# Generated by Django 5.2.5 on 2025-08-29 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociar_clientes_usuarios', '0003_initial'),
        ('clientes', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.segmento', verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(through='asociar_clientes_usuarios.AsignacionCliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
