# Generated by Django 5.2.6 on 2025-09-26 04:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('medios_pago', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(through='clientes.AsignacionCliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='clientemediodepago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='clientemediodepago',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medios_pago_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientemediodepago',
            name='medio_de_pago',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='medios_pago.mediodepago'),
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('segmento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.segmento', verbose_name='Segmento de Cliente')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Descuento aplicado (%)')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.segmento', verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='historialclientemediodepago',
            name='cliente_medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.clientemediodepago'),
        ),
        migrations.AddField(
            model_name='historialclientemediodepago',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialdescuentos',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacioncliente',
            unique_together={('usuario', 'cliente')},
        ),
        migrations.AddField(
            model_name='historialdescuentos',
            name='descuento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.descuento', verbose_name='Descuento'),
        ),
    ]
