# Generated by Django 5.2.6 on 2025-10-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclientemediodepago',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('MODIFICADO', 'Modificado'), ('ACTIVADO', 'Activado'), ('DESACTIVADO', 'Desactivado'), ('ELIMINADO', 'Eliminado')], max_length=20),
        ),
    ]
