# Generated by Django 5.2.6 on 2025-09-21 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('medios_pago', '0005_alter_campomediodepago_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_campos', models.JSONField(default=dict, help_text='Datos dinámicos según los campos del medio de pago')),
                ('es_activo', models.BooleanField(default=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es el medio de pago principal del cliente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medios_pago_creados', to=settings.AUTH_USER_MODEL)),
                ('medio_de_pago', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='medios_pago.mediodepago')),
            ],
            options={
                'verbose_name': 'Medio de Pago del Cliente',
                'verbose_name_plural': 'Medios de Pago de Clientes',
                'ordering': ['-es_principal', '-fecha_actualizacion'],
                'unique_together': {('cliente', 'medio_de_pago')},
            },
        ),
        migrations.CreateModel(
            name='HistorialClienteMedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado'), ('DESACTIVADO', 'Desactivado'), ('ACTIVADO', 'Activado')], max_length=20)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente_medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.clientemediodepago')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Medio de Pago',
                'verbose_name_plural': 'Historial de Medios de Pago',
                'ordering': ['-fecha'],
            },
        ),
    ]
