# Generated by Django 5.2.4 on 2025-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_segmento_alter_cliente_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
    ]
