# Generated by Django 5.2.4 on 2025-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha a la que aplica el límite', unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('inicio_vigencia', models.DateTimeField(help_text='Fecha y hora en que entra en vigencia el límite')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LimiteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Se guarda como el primer día del mes', unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inicio_vigencia', models.DateTimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-mes'],
            },
        ),
    ]
