# Generated by Django 5.2.6 on 2025-09-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientemediodepago_historialclientemediodepago'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientemediodepago',
            unique_together=set(),
        ),
    ]
