# Generated by Django 5.2.4 on 2025-09-04 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_comision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra_anterior', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Compra Anterior (%)')),
                ('valor_venta_anterior', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Venta Anterior (%)')),
                ('valor_compra_nuevo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Compra Nueva (%)')),
                ('valor_venta_nuevo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Venta Nueva (%)')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.comision', verbose_name='Comisión')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Historial de Comisión',
                'verbose_name_plural': 'Historial de Comisiones',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
