# Generated by Django 5.2.4 on 2025-09-26 16:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_limitediario_limitemensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitediario',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='limitemensual',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
