# Generated by Django 5.2.4 on 2025-09-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_esta_activo'),
        ('clientes', '0004_historialcomision'),
    ]

    operations = [
    ]
