# Generated by Django 5.2.4 on 2025-09-05 21:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_merge_0003_cliente_esta_activo_0004_historialcomision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcomision',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='historialcomision',
            name='modificado_por',
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('segmento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.segmento', verbose_name='Segmento de Cliente')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Descuento aplicado (%)')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='HistorialDescuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento_anterior', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento anterior (%)')),
                ('porcentaje_descuento_nuevo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nuevo descuento (%)')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.descuento', verbose_name='Descuento')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Historial de Descuento',
                'verbose_name_plural': 'Historial de Descuentos',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.DeleteModel(
            name='Comision',
        ),
        migrations.DeleteModel(
            name='HistorialComision',
        ),
    ]
