# Generated by Django 5.2.4 on 2025-09-06 00:49

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('simbolo', models.CharField(blank=True, default='', max_length=5, verbose_name='Símbolo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activa')),
                ('decimales', models.PositiveSmallIntegerField(default=2, verbose_name='Decimales')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
                'indexes': [models.Index(fields=['code'], name='divisas_div_code_e5a39b_idx'), models.Index(fields=['is_active'], name='divisas_div_is_acti_ba9de9_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='uniq_divisa_code_upper'), models.CheckConstraint(condition=models.Q(('decimales__gte', 0), ('decimales__lte', 8)), name='chk_divisa_decimales_0_8')],
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora')),
                ('precio_base', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio base')),
                ('comision_compra', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión aplicada en la compra', max_digits=5, verbose_name='Comisión compra (%)')),
                ('comision_venta', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión aplicada en la venta', max_digits=5, verbose_name='Comisión venta (%)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas', to='divisas.divisa')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['divisa', 'fecha'], name='divisas_tas_divisa__bff05e_idx')],
            },
        ),
    ]
