# Generated by Django 5.2.4 on 2025-09-03 03:58

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('simbolo', models.CharField(blank=True, default='', max_length=5, verbose_name='Símbolo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activa')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
                'indexes': [models.Index(fields=['code'], name='divisas_div_code_e5a39b_idx'), models.Index(fields=['is_active'], name='divisas_div_is_acti_ba9de9_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='uniq_divisa_code_upper')],
            },
        ),
    ]
