# Generated by Django 5.2.4 on 2025-09-25 23:21

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('simbolo', models.CharField(blank=True, default='', max_length=5, verbose_name='Símbolo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activa')),
                ('decimales', models.PositiveSmallIntegerField(default=2, verbose_name='Decimales')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
                'indexes': [models.Index(fields=['code'], name='divisas_div_code_e5a39b_idx'), models.Index(fields=['is_active'], name='divisas_div_is_acti_ba9de9_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='uniq_divisa_code_upper'), models.CheckConstraint(condition=models.Q(('decimales__gte', 0), ('decimales__lte', 8)), name='chk_divisa_decimales_0_8')],
            },
        ),
        migrations.CreateModel(
            name='CotizacionSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_base', models.DecimalField(decimal_places=8, max_digits=20)),
                ('comision_compra', models.DecimalField(decimal_places=8, max_digits=20)),
                ('comision_venta', models.DecimalField(decimal_places=8, max_digits=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_compra_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('valor_venta_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.segmento')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa')),
            ],
            options={
                'verbose_name': 'Cotización por segmento',
                'verbose_name_plural': 'Cotizaciones por segmento',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='divisas_cot_fecha_f8c972_idx'), models.Index(fields=['divisa', 'segmento', 'fecha'], name='divisas_cot_divisa__f24257_idx')],
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('precio_base', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Precio base')),
                ('comision_compra', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Comisión compra')),
                ('comision_venta', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Comisión venta')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas', to='divisas.divisa')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['divisa', 'fecha'], name='divisas_tas_divisa__bff05e_idx')],
            },
        ),
    ]
