# Generated by Django 5.2.4 on 2025-09-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor_compra', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor de compra')),
                ('valor_venta', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor de venta')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas', to='divisas.divisa')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['divisa', 'fecha'], name='divisas_tas_divisa__bff05e_idx')],
                'constraints': [models.UniqueConstraint(fields=('divisa', 'fecha'), name='uniq_divisa_fecha')],
            },
        ),
    ]
