# Generated by Django 5.2.6 on 2025-09-26 11:34

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('divisas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionsegmento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionsegmento',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.segmento'),
        ),
        migrations.AddIndex(
            model_name='divisa',
            index=models.Index(fields=['code'], name='divisas_div_code_e5a39b_idx'),
        ),
        migrations.AddIndex(
            model_name='divisa',
            index=models.Index(fields=['is_active'], name='divisas_div_is_acti_ba9de9_idx'),
        ),
        migrations.AddConstraint(
            model_name='divisa',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='uniq_divisa_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='divisa',
            constraint=models.CheckConstraint(condition=models.Q(('decimales__gte', 0), ('decimales__lte', 8)), name='chk_divisa_decimales_0_8'),
        ),
        migrations.AddField(
            model_name='cotizacionsegmento',
            name='divisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa'),
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='divisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas', to='divisas.divisa'),
        ),
        migrations.AddIndex(
            model_name='cotizacionsegmento',
            index=models.Index(fields=['fecha'], name='divisas_cot_fecha_f8c972_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacionsegmento',
            index=models.Index(fields=['divisa', 'segmento', 'fecha'], name='divisas_cot_divisa__f24257_idx'),
        ),
        migrations.AddIndex(
            model_name='tasacambio',
            index=models.Index(fields=['divisa', 'fecha'], name='divisas_tas_divisa__bff05e_idx'),
        ),
    ]
