# Generated by Django 5.2.4 on 2025-09-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambio',
            name='comision_compra',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Comisión compra'),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='comision_venta',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Comisión venta'),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='precio_base',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Precio base'),
        ),
    ]
