# Generated by Django 5.2.6 on 2025-10-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisa',
            name='es_moneda_base',
            field=models.BooleanField(default=False, editable=False, verbose_name='Moneda Base'),
        ),
        migrations.AddIndex(
            model_name='divisa',
            index=models.Index(fields=['es_moneda_base'], name='divisas_div_es_mone_13a367_idx'),
        ),
    ]
