# Generated by Django 5.2.4 on 2025-09-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0002_tasacambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisa',
            name='decimales',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Decimales'),
        ),
        migrations.AddConstraint(
            model_name='divisa',
            constraint=models.CheckConstraint(condition=models.Q(('decimales__gte', 0), ('decimales__lte', 8)), name='chk_divisa_decimales_0_8'),
        ),
    ]
