# Generated by Django 5.2.4 on 2025-09-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0002_tasacambio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tasacambio',
            name='uniq_divisa_fecha',
        ),
        migrations.AddConstraint(
            model_name='tasacambio',
            constraint=models.UniqueConstraint(fields=('divisa', 'fecha'), name='unique_tasa_por_divisa_fecha'),
        ),
    ]
