# Generated by Django 5.2.4 on 2025-09-06 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_historialcomision_comision_and_more'),
        ('divisas', '0002_alter_tasacambio_comision_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_base', models.DecimalField(decimal_places=8, max_digits=20)),
                ('comision_compra', models.DecimalField(decimal_places=8, max_digits=20)),
                ('comision_venta', models.DecimalField(decimal_places=8, max_digits=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_compra_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('valor_venta_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisas.divisa')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.segmento')),
            ],
            options={
                'verbose_name': 'Cotización por segmento',
                'verbose_name_plural': 'Cotizaciones por segmento',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='divisas_cot_fecha_f8c972_idx'), models.Index(fields=['divisa', 'segmento', 'fecha'], name='divisas_cot_divisa__f24257_idx')],
            },
        ),
    ]
