# Generated by Django 5.2.6 on 2025-10-15 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0002_initial'),
        ('transacciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=8, help_text='Valor del billete o moneda (ej: 100, 50, 20, etc.)', max_digits=20, verbose_name='Valor nominal')),
                ('tipo', models.CharField(choices=[('billete', 'Billete'), ('moneda', 'Moneda')], default='billete', max_length=10, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta denominación está disponible para entrega', verbose_name='Activa')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor valor = mayor prioridad)', verbose_name='Orden')),
                ('color', models.CharField(default='#6c757d', help_text='Color hexadecimal para visualización (ej: #28a745)', max_length=7, verbose_name='Color de referencia')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre esta denominación', verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='divisas.divisa', verbose_name='Divisa')),
            ],
            options={
                'verbose_name': 'Denominación',
                'verbose_name_plural': 'Denominaciones',
                'ordering': ['divisa', '-valor'],
            },
        ),
        migrations.CreateModel(
            name='DesgloseDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de billetes/monedas de esta denominación', verbose_name='Cantidad')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='divisas.denominacion', verbose_name='Denominación')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose_denominaciones', to='transacciones.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Desglose de denominación',
                'verbose_name_plural': 'Desgloses de denominaciones',
                'ordering': ['-denominacion__valor'],
            },
        ),
        migrations.AddIndex(
            model_name='denominacion',
            index=models.Index(fields=['divisa', 'is_active'], name='divisas_den_divisa__352bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='denominacion',
            index=models.Index(fields=['divisa', 'valor'], name='divisas_den_divisa__1d3f61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='denominacion',
            unique_together={('divisa', 'valor', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='desglosedenominacion',
            unique_together={('transaccion', 'denominacion')},
        ),
    ]
