# Generated by Django 5.2.4 on 2025-09-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0003_divisa_decimales_divisa_chk_divisa_decimales_0_8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasacambio',
            name='valor_compra',
        ),
        migrations.RemoveField(
            model_name='tasacambio',
            name='valor_venta',
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='precio_base',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Precio base'),
            preserve_default=False,
        ),
    ]
