# Generated by Django 5.2.6 on 2025-10-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0003_denominacion_desglosedenominacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominacion',
            name='color',
            field=models.CharField(default='#000000', help_text='Color hexadecimal para visualización (ej: #28a745)', max_length=7, verbose_name='Color de referencia'),
        ),
        migrations.AlterField(
            model_name='denominacion',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor del billete o moneda (ej: 100, 50, 20, etc.)', max_digits=50, verbose_name='Valor nominal'),
        ),
    ]
