# Generated by Django 5.2.4 on 2025-09-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0004_tasacambio_creado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasacambio',
            name='creado_por',
        ),
    ]
