# Generated by Django 5.2.6 on 2025-10-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0004_alter_denominacion_color_alter_denominacion_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominacion',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Orden de visualización (se calcula automáticamente según el valor)', null=True, verbose_name='Orden'),
        ),
    ]
