# Generated by Django 5.2.6 on 2025-10-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0005_alter_denominacion_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominacion',
            name='tipo',
            field=models.CharField(choices=[('billete', 'Billete')], default='billete', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='denominacion',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor del billete (ej: 100, 50, 20, etc.)', max_digits=50, verbose_name='Valor nominal'),
        ),
        migrations.AlterField(
            model_name='desglosedenominacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de billetes de esta denominación', verbose_name='Cantidad'),
        ),
    ]
