# Generated by Django 5.2.6 on 2025-10-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0006_alter_denominacion_tipo_alter_denominacion_valor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='denominacion',
            unique_together={('divisa', 'valor')},
        ),
        migrations.RemoveField(
            model_name='denominacion',
            name='color',
        ),
        migrations.RemoveField(
            model_name='denominacion',
            name='tipo',
        ),
    ]
