# Generated by Django 5.2.6 on 2025-10-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominacion',
            name='valor',
            field=models.DecimalField(decimal_places=8, help_text='Valor del billete (ej: 100, 50, 20, etc.)', max_digits=20, verbose_name='Valor nominal'),
        ),
    ]
