# Generated by Django 5.2.6 on 2025-09-30 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_celular', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billeteras', to='banco.entidadbancaria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera', to='billetera.usuariobilletera')),
            ],
            options={
                'unique_together': {('usuario', 'entidad')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECARGA', 'Recarga'), ('ENVIO', 'Envío'), ('RECEPCION', 'Recepción')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(default='Sin descripción')),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='billetera.billetera')),
                ('billetera_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_recibidos', to='billetera.billetera')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RecargaBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitosa', models.BooleanField(default=False)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='billetera.billetera')),
                ('tarjeta_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.tarjetadebito')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitosa', models.BooleanField(default=False)),
                ('billetera_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='billetera.billetera')),
                ('billetera_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='billetera.billetera')),
            ],
        ),
    ]
