# Generated by Django 5.2.4 on 2025-09-26 05:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('color_principal', models.CharField(default='#1d3557', max_length=7)),
                ('color_secundario', models.CharField(default='#457b9d', max_length=7)),
                ('logo_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='billeterauser',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='billetera.entidadbilletera'),
        ),
        migrations.CreateModel(
            name='MovimientoBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECARGA', 'Recarga'), ('ENVIO', 'Envío'), ('RECEPCION', 'Recepción')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='billetera.billetera')),
            ],
        ),
        migrations.DeleteModel(
            name='TransferenciaBilleteraABanco',
        ),
    ]
