# Generated by Django 5.2.4 on 2025-09-26 06:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0007_remove_pagotarjeta_cuenta_remove_pagotarjeta_tarjeta_and_more'),
        ('billetera', '0002_entidadbilletera_billeterauser_entidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_celular', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='billeterauser',
            name='entidad',
        ),
        migrations.AlterModelOptions(
            name='movimientobilletera',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='billetera',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='billetera',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billeteras', to='banco.entidadbancaria'),
        ),
        migrations.AddField(
            model_name='billetera',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movimientobilletera',
            name='billetera_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_recibidos', to='billetera.billetera'),
        ),
        migrations.AlterField(
            model_name='movimientobilletera',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='movimientobilletera',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='RecargaBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitosa', models.BooleanField(default=False)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='billetera.billetera')),
                ('tarjeta_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.tarjetadebito')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitosa', models.BooleanField(default=False)),
                ('billetera_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='billetera.billetera')),
                ('billetera_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='billetera.billetera')),
            ],
        ),
        migrations.AlterField(
            model_name='billetera',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera', to='billetera.usuariobilletera'),
        ),
        migrations.AlterUniqueTogether(
            name='billetera',
            unique_together={('usuario', 'entidad')},
        ),
        migrations.DeleteModel(
            name='EntidadBilletera',
        ),
        migrations.DeleteModel(
            name='BilleteraUser',
        ),
    ]
