# Generated by Django 5.2.6 on 2025-09-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comision_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.moneda')),
            ],
        ),
    ]
